copy-community/config/routes.rb
Community::Application.routes.draw do
  devise_for :members,:controllers => { :registrations =>'registration'}

match 'dashboard' => 'home#dashboard'

  match 'register' =>'registration#register'
  
  root :to => 'home#index'

end

copy-community/app/models/contact.rb
class Contact < ActiveRecord::Base

  belongs_to :member
  
end

copy-community/app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  has_one :contact
end

copy-community/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

copy-community/app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
   @contact = Contact.new
  end
end

copy-community/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end
end

copy-community/app/controllers/registration_controller.rb
class RegistrationController < Devise::RegistrationsController

def new
    #super
    @member= Member.new
    @contact = Contact.new
  end

  def create

    @member = Member.new
    @member.username = params[:member][:username]
    @member.email = params[:member][:email]
    @member.password = params[:member][:password]
    @member.password_confirmation =params[:member][:password_confirmation]
    
    @contact = Contact.new
    @contact.mobile = params[:contact][:mobile]
    @contact.address = params[:contact][:address]
    @member.valid?


    if @member.errors.blank?

     @member.save 
     @contact.member = @member
     @contact.save
     
      flash[:notice] = "created"
      redirect_to dashboard_path
    else
     render :action => "new"
    end
    end
     
end

copy-community/app/helpers/application_helper.rb
module ApplicationHelper
end

copy-community/app/helpers/contact_helper.rb
module ContactHelper
end

copy-community/app/helpers/home_helper.rb
module HomeHelper
end

copy-community/app/helpers/registration_helper.rb
module RegistrationHelper
end

copy-community/app/views/home/dashboard.html.erb
  <h1>welcome to Ruby community you have successfully logged in</h1>
  <%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>
  

copy-community/app/views/home/index.html.erb
<% if member_signed_in? %>

  
  <h3>you have succesfully signed in</h3>
  <%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>
  

<% else %>

  
<h1>Rails Club</h1>
Jan 1, 2012	sreehari k m
<div class="CL"></div>

<img src="/images/rails.png" />

<p>
I’m sreehari ,this is just small aplication created by using rails with devise,
</p>
<p>
Ruby on Rails, often shortened to Rails or RoR, is an open source full-stack web application framework for the Ruby programming language. Ruby on Rails is not to be confused with Ruby, which is a general purpose programming language that Ruby on Rails runs on. It should also be noted that Ruby itself existed for more than 10 years before the first release of Ruby on Rails. Ruby on Rails is a full-stack framework, meaning, it gives the web developer the full ability to gather information from the web server, talking/querying the database, and template rendering out of the box, also, as a result, Rails features a routing system that is independent of the web server.
</p>
<p>
Ruby on Rails was extracted by David Heinemeier Hansson from his work on Basecamp, a project management tool by 37signals (now a web application company).Hansson first released Ruby on Rails as open source in July 2004, but did not share commit rights to the project until February 2005. In August 2006 the framework reached a milestone when Apple announced that it would ship Ruby on Rails with Mac OS X v10.5 "Leopard", which was released in October 2007.
</p>

<p>
In a default configuration, a model in a Ruby on Rails framework maps to a table in a database. By convention, a model named User will map to the database table users, and the model will have a filename user.rb within app/models, while developers can choose to use whatever model name and database table name they wish, this is not a common practice and it's usually discouraged because Rails philosophy is to use convention over configuration.
</p>

<p>
A controller is the component of Rails that responds to external request from the web server to the application, and respond to the external request by determining which view file to render. The controller may also have to query the model directly for information and pass these onto the view. A controller may contain one or more actions. In Ruby on Rails, action is typically a basic unit which describing a single rule on how to respond to a specific external web-browser request. Also note that, if a controller/action is not mapped to the Rails router, the controller/action will be directly inaccessible to external web requests. By convention, Rails encourage developers to use a RESTful route which contain actions named create, new, edit, update, destroy, and index, as these are routed automatically by convention in the routes file if specified.</p>

<p>
A view typically is a erb file in the default configuration of Rails. It is typically converted to output html at run-time, although in theory any formats can be used as a view.
</p>

<% end %>

copy-community/app/views/layouts/_footer.erb
<div class="FOOTER">
	<center><h5 style="color:white ;margin: 5px 0px;">Copyright sreehari@presciecesoft.com</h5></center>
</div>

copy-community/app/views/layouts/_header.erb
<div class="HEADER">
	<center><h1 style="color:#990000;margin: 5px 0px;">Rails Club - Where enthusiasts meet</h1></center>
	<div class="SHELL">
		<div class="FLOAT_LEFT">
			<%= link_to "Home", root_path %>
	    </div>
		<div class="FLOAT_RIGHT">
		<% if current_member %>
			Welcome <b style="color: #38761d;"><%= current_member.username || current_member.email %></b>&nbsp;|&nbsp;
			<%= link_to "Sign Out", destroy_member_session_path, :method=>:delete %>
		<% else %>
			<%= link_to "Sign In", new_member_session_path(current_member) %>&nbsp;|&nbsp;
			<%= link_to "Register", new_member_registration_path(current_member) %>
		<% end %>
		</div>
	</div>
</div>

copy-community/app/views/layouts/_notice.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

copy-community/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Community</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<body>
	<%= render :partial=>"/layouts/header" %>
	
	<div class="SHELL">
		<%= render :partial=>"/layouts/notice" %>
		<div class="CL"></div>
		<%= yield %>
		<div class="CL"></div>
	</div>
	
	<%= render :partial=>"/layouts/footer" %>

</body>
</html>